spring.application.name=petvida

# H2 em memoria
spring.datasource.url=jdbc:h2:mem:petvida
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Exigidas pela prova (evidencia nas Partes C e F)
logging.level.web=trace
spring.thymeleaf.cache=false
